### ISSUE TITLE
API 요청을 크론으로 요청하였을 때 아래 에러가 발생하였습니다. 예외 처리를 추가해야 될 것으로 보입니다.

### ISSUE THREAD

**Issue by t0e8r1r4y** [t0e8r1r4y/NaverAPI#1]
- 아래 내용이 얼마나 주기적으로 발생하는지?
- 발생한 내용에서 비즈니스로직과 관련하여 처리 방법을 고민해야 될 것으로 보입니다.

java.lang.RuntimeException: API 응답을 읽는 데 실패했습니다.
	at com.naverapi.naverapi.component.api.NaverSearchApi.readBody(NaverSearchApi.java:98) ~[classes/:na]
	at com.naverapi.naverapi.component.api.NaverSearchApi.get(NaverSearchApi.java:58) ~[classes/:na]
	at com.naverapi.naverapi.component.api.NaverSearchApi.search(NaverSearchApi.java:39) ~[classes/:na]
	at com.naverapi.naverapi.application.service.NaverApiService.parseAndSave(NaverApiService.java:105) ~[classes/:na]
	at com.naverapi.naverapi.application.service.NaverApiService$$FastClassBySpringCGLIB$$241c3f47.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.23.jar:5.3.23]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.23.jar:5.3.23]
	at com.naverapi.naverapi.application.service.NaverApiService$$EnhancerBySpringCGLIB$$e85224f9.parseAndSave(<generated>) ~[classes/:na]
	at com.naverapi.naverapi.component.schedule.NaverApiScheduler.naverApiTest(NaverApiScheduler.java:24) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) [spring-context-5.3.23.jar:5.3.23]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_292]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_292]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]
Caused by: javax.net.ssl.SSLException: Read timed out
	at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[na:1.8.0_292]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[na:1.8.0_292]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[na:1.8.0_292]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[na:1.8.0_292]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:138) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1386) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1354) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:948) ~[na:1.8.0_292]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_292]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_292]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_292]
	at sun.net.www.http.ChunkedInputStream.fastRead(ChunkedInputStream.java:244) ~[na:1.8.0_292]
	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:689) ~[na:1.8.0_292]
	at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[na:1.8.0_292]
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3454) ~[na:1.8.0_292]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_292]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_292]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_292]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_292]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[na:1.8.0_292]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[na:1.8.0_292]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[na:1.8.0_292]
	at com.naverapi.naverapi.component.api.NaverSearchApi.readBody(NaverSearchApi.java:91) ~[classes/:na]
	... 24 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_292]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_292]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_292]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:457) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:237) ~[na:1.8.0_292]
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190) ~[na:1.8.0_292]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109) ~[na:1.8.0_292]
	... 43 common frames omitted

**Comment by t0e8r1r4y** [comment]
우선 위 현상이 발생하여도 프로세스가 종료되지 않도록 설정 후 지속 실행.

**Comment by t0e8r1r4y** [comment]
예외처리 완료
